services:
  db:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
