server:
  port: 8081
  servlet:
    context-path: /search

spring:
  application:
    name: search-service
  datasource:
    url: jdbc:postgresql://localhost:5432/atom
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

  redis:
    host: localhost
    port: 6379
    timeout: 2000
    ttl: 300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: search-service
    prefer-ip-address: true
#    instance-id: ${server.host}:${eureka.instance.appname}:${server.port}